url: https://linux98.ir

language: fa_IR
direction: rtl
charset: UTF-8



title: لینوکس ۹۸
description: منبع فارسی لینوکس و نرم افزارهای متن باز

disqus_shortname: linux98
disqus_language: fa

feedburner: linux98

# Google custom search engine
google_cse: f7004dddd1e4d598d

google_analytics: G-SNHZJ4G2ZX

excerpt_separator: '<div id="read-more"></div>'

permalink: /:year/:month/:slug/

# future post disabled
future: false

collections:
    pages:
        output: true
        permalink: /:slug/
    statics:
        output: true
        permalink: /:path


exclude:
    - CNAME
    - README.md


plugins:
    - jekyll-paginate
    - jekyll-seo-tag
    - jekyll-sitemap
    - jemoji
    - jekyll-feed

google_site_verification: cq6a3Ab_v7AW1E_BlWFNW_uwNWoHpiN4x-LVBe1MaRQ

paginate: 10
paginate_path: /page/:num/
